### PR TITLE
typo: "an very" to "a very"

### PR DESCRIPTION
**Pull request by ajschumacher**

### CODE REVIEW

**Comment by ajschumacher** [comment]
@colah ping

**Comment by ajschumacher** [comment]
@colah ping ping

**Comment by colah** [comment]
Thanks. Sorry about delayed response; I've been very busy with work and personal stuff.

**Comment by ajschumacher** [comment]
No worries! Just a silly thing - wanted to get it off the new dashboard; thanks a lot! :smile:

**Pull request merged**
